Repository capsulajs/capsulahub, pull requests merged in 2019-08, with the labels that each got.

#28 Add timestamp to RequestForm to improve external updates of content
  packages/ui/src/components/request-form/request-form.js
Labels: Please review me! ;)

#29 Workspace should not fail on extension error
  packages/service-renderer/src/RendererService.ts
  packages/utils/src/helpers.tsx
  packages/workspace/README.md
  packages/workspace/package.json
  packages/workspace/src/Workspace.ts
  packages/workspace/src/WorkspaceFactory.ts
  packages/workspace/src/helpers/const.ts
  packages/workspace/src/helpers/eventEmitters.ts
  packages/workspace/src/helpers/types.ts
  packages/workspace/src/helpers/utils.ts
  packages/workspace/tests/features/workspace.feature
  packages/workspace/tests/helpers/const.ts
  packages/workspace/tests/helpers/mocks.ts
  packages/workspace/tests/helpers/utils.ts
  packages/workspace/tests/implementations/workspace.test.ts
Labels: Please review me! ;)

#34 [Feature] Removed default title
  packages/cli/app/index.html
Labels: enhancement

#35 update scalecube dependencies
  packages/workspace/package.json
  packages/workspace/src/Workspace.ts
  packages/workspace/src/api/ServiceConfig.ts
  packages/workspace/tests/helpers/baseConfigEntries.ts
  yarn.lock
Labels: Please review me! ;), dependencies
